config/routes.rb
BuddyBuildTracker::Application.routes.draw do
  resources :emails
  resources :bugs
  resources :users, :constraints => { :id => /[^\/]*/ }
  

  root :to => 'bugs#index'

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :requestor, :class_name => "User"
  belongs_to :tester,    :class_name => "User"
  has_many :emails

  attr_accessible :tfs_id, :status, :drop_folder, :requestor, :tester
  validates :tfs_id,        :presence => true
  validate :requestor_role, :unless => "requestor_id.nil?"
  validate :tester_role,    :unless => "tester_id.nil?"

  def to_param
    self.tfs_id
  end

  def link_to_tfs
    "http://vstfbing:8080/tfs/Bing/AppEx/_workItems#_a=edit&id=#{self.tfs_id}"
  end

  def requestor_role
    requestor.role != 'developer' && errors.add(:requestor, "not a developer")
  end

  def tester_role
    tester.role != 'tester' && errors.add(:tester, "not a tester")
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :bug

  serialize :from, Array
  serialize :to, Array
  serialize :cc, Array
  attr_accessible :body, :from, :raw_body, :status, :subject, :to, :cc, :date
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users

  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :emails
  has_many :tester_bugs,    :class_name => 'Bug', :foreign_key => 'tester_id'
  has_many :requestor_bugs, :class_name => 'Bug', :foreign_key => 'requestor_id'

  attr_accessible :email, :name, :role, :alias

  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  after_validation :fill_alias

  def to_param
    self.alias
  end

  def fill_alias
    if self.alias.nil? and not self.email.nil?
      self.alias = (self.email.match /(.*)@/)[1]
    end
  end

  def bugs
    [self.tester_bugs + self.requestor_bugs].flatten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def index
    @bugs = Bug.all

    respond_to do |format|
      format.html
      format.json { render json: @bugs }
    end
  end

  def show
    @bug = Bug.find_by_tfs_id(params[:id])
  end

  def edit
    @bug = Bug.find_by_tfs_id(params[:id])
  end

  def update
    @bug = Bug.find_by_tfs_id(params[:id])

    respond_to do |format|
      if @bug.update_attributes(params[:bug])
        format.html { redirect_to @bug, notice: 'bug was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def index
    @emails = Email.all

    respond_to do |format|
      format.html
      format.json { render json: @emails }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find_by_alias("#{params[:id]}") || not_found
    #@user = User.find(params[:id]) || User.find_by_alias(params[:alias]) || not_found
  end

  def edit
    @user = User.find_by_alias(params[:id]) || not_found
    #@user = User.find(params[:id]) || User.find_by_alias(params[:alias]) || not_found
  end

  def update
    @user = User.find_by_alias(params[:id]) || not_found
    #@user = User.find(params[:id]) || User.find_by_alias(params[:alias]) || not_found

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def not_found
    #raise ActionController::RoutingError.new('Not Found')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bugs/_form.html.erb
<%= form_for(@bug) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tfs_id %><br />
    <%= f.text_field :tfs_id %>
  </div>

  <div class="field">
    <%= f.label :drop_folder %><br />
    <%= f.text_field :drop_folder %>
  </div>

  <div class="field">
    <%= f.label :requestor_id %><br />
    <%= f.collection_select :requestor_id, User.find_all_by_role('developer'), :id, :name %>
  </div>

  <div class="field">
    <%= f.label :tester_id %><br />
    <%= f.collection_select :tester_id, User.find_all_by_role('tester'), :id, :name %>
  </div>

  <div class="field">
    <%= f.label :status %><br />
    <%= select(:bug, :status, %w[unknown pending ready]) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1>Editing bug</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/index.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>TFS ID</th>
    <th>Status</th>
    <th>Drop folder</th>
    <th>Requestor</th>
    <th>Tester</th>
    <th>Buttons</th>
  </tr>
<% @bugs.each do |bug| %>
  <tr>
    <td><%= bug.id %></td>
    <td><%= link_to bug.tfs_id, bug.link_to_tfs %></td>
    <td><%= bug.status %></td>
    <td><%= bug.drop_folder %></td>
    <td><%= bug.requestor.name if bug.requestor %></td>
    <td><%= bug.tester.name    if bug.tester %></td>
    <td><%= link_to 'Show', bug %> <%= link_to 'Edit', edit_bug_path(bug) %></td>
  </tr>
<% end %>

</table>

<%= link_to "New bug", new_bug_path %>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form' %>

<%= link_to 'Back', promotions_path %>

app/views/bugs/show.html.erb
TFS ID:  <%= @bug.tfs_id %>  <br>
Status:  <%= @bug.status %> <br>
Requestor:  <%= @bug.requestor.name %> <br>
Tester:  <%= @bug.tester.name %> <br>


<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuddyBuildTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :alias %><br />
    <%= f.text_field :alias %>
  </div>

  <div class="field">
    <%= f.label :role %><br />
    <%= select(:user, :role, %w[unknown developer tester]) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Alias</th>
    <th>Email</th>
    <th>Role</th>
    <th>Bug count</th>
    <th>Links</th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.alias %></td>
    <td><%= user.email %></td>
    <td><%= user.role %></td>
    <td><%= user.bugs.count %></td>
    <td><%= link_to 'Show', user %> <%= link_to 'Edit', edit_user_path(user.alias) %></td>
  </tr>
<% end %>

</table>

app/views/users/show.html.erb
Name:  <%= @user.name %>  <br>
Alias: <%= @user.alias %> <br>
Email: <%= @user.email %> <br>
Role:  <%= @user.role %>  <br>
Bugs:  <%= @user.bugs %> <br>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>